project_name: eHabitat
runner_class: PythonRunner
 
base_params:
    shared_dir: \\LONGORIA\export\test
    output_dir2: e:\

    # path_to_library_code: $$library_path(r-library)$$/some_path
    # a_useful_input_file: $$input_path$$useful.txt
    # another_useful_input_file: $$input_path$$also_useful.txt
    output_dir: $$output_path$$
    ecoreg_id: 10105
    # a_string_array: [abc,def,ghi]
    # another_array:
     #    - 1
     #    - 2
       

repetitions:
    
    generators:
      - key: ecoreg_id
        generator_type: linear_step
        start: 4
        step_size: 1
        count: 2
 
 
mapreduce:
  mapper_class: FileCopier
  mapper_flags:
    source_filename: hri_results.csv
    dest_filename: all_hri_results.csv
  reducer_class: Concatenator
  reducer_flags:
    heading_row: true
 
# This stanza is equivalent to the one above, but is simpler
# to understand.
# concatenate:
#   heading_row: true
#   input_filename: hri_results.csv
#   output_filename: all_hri_results.csv
